//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMarketLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDelivery
    {
        public int Product { get; set; }
        public int Delivery { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Delivery Delivery1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
